name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Install
      run: yarn install
          
    - name: lint
      run: yarn lint
      
    - name: test
      run: yarn test

    - name: build
      run: yarn build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build